  {0, "(.*)*\\1", "xx", { "xx", "x" } },
  {0, "^", "", {""} },
  {0, "$", "", {""} },
  {0, "^$", "", {""} },
  {0, "^a$", "a", {"a"} },
  {0, "abc", "abc", {"abc"} },
  {1, "abc", "xbc"},
  {1, "abc", "axc"},
  {1, "abc", "abx"},
  {0, "abc", "xabcy", {"abc"} },
  {0, "abc", "ababc", {"abc"} },
  {0, "ab*c", "abc", {"abc"} },
  {0, "ab*bc", "abc", {"abc"} },
  {0, "ab*bc", "abbc", {"abbc"} },
  {0, "ab*bc", "abbbbc", {"abbbbc"} },
  {0, "ab+bc", "abbc", {"abbc"} },
  {1, "ab+bc", "abc"},
  {1, "ab+bc", "abq"},
  {0, "ab+bc", "abbbbc", {"abbbbc"} },
  {0, "ab?bc", "abbc", {"abbc"} },
  {0, "ab?bc", "abc", {"abc"} },
  {1, "ab?bc", "abbbbc"},
  {0, "ab?c", "abc", {"abc"} },
  {0, "^abc$", "abc", {"abc"} },
  {1, "^abc$", "abcc"},
  {0, "^abc", "abcc", {"abc"} },
  {1, "^abc$", "aabc"},
  {0, "abc$", "aabc", {"abc"} },
  {0, "^", "abc", {""} },
  {0, "$", "abc", {""}},
  {0, "a.c", "abc", {"abc"} },
  {0, "a.c", "axc", {"axc"} },
  {0, "a.*c", "axyzc", {"axyzc"} },
  {1, "a.*c", "axyzd"},
  {1, "a[bc]d", "abc"},
  {0, "a[bc]d", "abd", {"abd"}},
  {1, "a[b-d]e", "abd"},
  {0, "a[b-d]e", "ace", {"ace"}},
  {0, "a[b-d]", "aac", {"ac"}},
  {0, "a[-b]", "a-", {"a-"}},
  {0, "a[b-]", "a-", {"a-"}},
  {2, "a[b-a]", "-"},
  {2, "a[]b", "-"},
  {2, "a[", "-"},
  {0, "a]", "a]", {"a]"}},
  {0, "a[]]b", "a]b", {"a]b"}},
  {0, "a[^bc]d", "aed", {"aed"}},
  {1, "a[^bc]d", "abd"},
  {0, "a[^-b]c", "adc", {"adc"}},
  {1, "a[^-b]c", "a-c"},
  {1, "a[^]b]c", "a]c"},
  {0, "a[^]b]c", "adc", {"adc"}},
  {0, "ab|cd", "abc", {"abc"}},
  {0, "ab|cd", "abcd", {"abcd"}},
  {0, "()ef", "def", {"ef",""}},
  {0, "()*", "-", {"",""}},
  {2, "*a", "-"},
  {2, "^*", "-"},
  {2, "$*", "-"},
  {2, "(*)b", "-"},
  {1, "$b", "b"},
  {2, "a\\", "-"},
  {0, "a\\(b", "a(b", {"a(b"}},
  {0, "a\\(*b", "ab", {"ab"}},
  {0, "a\\(*b", "a((b", {"a((b"}},
  {1, "a\\x", "a\\x"},
  {1, "abc)", "-"},
  {2, "(abc", "-"},
  {0, "((a))", "abc", {"a", "a", "a"}},
  {0, "(a)b(c)", "abc", {"abc", "a", "c"}},
  {0, "a+b+c", "aabbabc", {"abc"}},
  {0, "a**", "-", {""}},
  {0, "a*?", "-", {""}},
  {0, "(a*)*", "-", {"", ""}},
  {0, "(a*)+", "-", {"", ""}},
  {0, "(a|)*", "-", {"", ""}},
  {0, "(a*|b)*", "-", {"", ""}},
  {0, "(a+|b)*", "ab", {"ab", "b"}},
  {0, "(a+|b)+", "ab", {"ab", "b"}},
  {0, "(a+|b)?", "ab", {"a", "a"}},
  {0, "[^ab]*", "cde", {"cde"}},
  {0, "(^)*", "-", {""}},
  {0, "(ab|)*", "-", {"", ""}},
  {2, ")(", "-"},
  {1, "abc", ""},
  {1, "abc", ""},
  {0, "a*", "", {""}},
  {0, "([abc])*d", "abbbcd", {"abbbcd", "c"}},
  {0, "([abc])*bcd", "abcd", {"abcd", "a"}},
  {0, "a|b|c|d|e", "e", {"e"}},
  {0, "(a|b|c|d|e)f", "ef", {"ef", "e"}},
  {0, "((a*|b))*", "-", {"", "", ""}},
  {0, "abcd*efg", "abcdefg", {"abcdefg"}},
  {0, "ab*", "xabyabbbz", {"abbb"}},
  {0, "ab*", "xayabbbz", {"abbb"}},
  {0, "(ab|cd)e", "abcde", {"cde", "cd"}},
  {0, "[abhgefdc]ij", "hij", {"hij"}},
  {1, "^(ab|cd)e", "abcde"},
  {0, "(abc|)ef", "abcdef", {"ef", ""}},
  {0, "(a|b)c*d", "abcd", {"bcd", "b"}},
  {0, "(ab|ab*)bc", "abc", {"abc", "ab"}},
  {0, "a([bc]*)c*", "abc", {"abc", "bc"}},
  {0, "a([bc]*)(c*d)", "abcd", {"abcd", "bc", "d"}},
  {0, "a([bc]+)(c*d)", "abcd", {"abcd", "bc", "d"}},
  {0, "a([bc]*)(c+d)", "abcd", {"abcd", "b", "cd"}},
  {0, "a[bcd]*dcdcde", "adcdcde", {"adcdcde"}},
  {1, "a[bcd]+dcdcde", "adcdcde"},
  {0, "(ab|a)b*c", "abc", {"abc", "ab"}},
  {0, "((a)(b)c)(d)", "abcd", {"abcd", "abc", "a", "b", "d"}},
  {0, "[A-Za-z_][A-Za-z0-9_]*", "alpha", {"alpha"}},
  {0, "^a(bc+|b[eh])g|.h$", "abh", {"bh"}},
  {0, "(bc+d$|ef*g.|h?i(j|k))", "effgz", {"effgz", "effgz"}},
  {0, "(bc+d$|ef*g.|h?i(j|k))", "ij", {"ij", "ij", "j"}},
  {1, "(bc+d$|ef*g.|h?i(j|k))", "effg"},
  {1, "(bc+d$|ef*g.|h?i(j|k))", "bcdd"},
  {0, "(bc+d$|ef*g.|h?i(j|k))", "reffgz", {"effgz", "effgz"}},
  {1, "((((((((((a))))))))))", "-"},
  {0, "(((((((((a)))))))))", "a", {"a", "a", "a", "a", "a", "a", "a", "a", "a", "a"}},
  {1, "multiple words of text", "uh-uh"},
  {0, "multiple words", "multiple words, yeah", {"multiple words"}},
  {0, "(.*)c(.*)", "abcde", {"abcde", "ab", "de"}},
  {1, "\\((.*),", "(.*)\\)"},
  {1, "[k]", "ab"},
  {0, "abcd", "abcd", {"abcd"}},
  {0, "a(bc)d", "abcd", {"abcd", "bc"}},
  {0, "a[-]?c", "ac", {"ac"}},
  {0, "(....).*\\1", "beriberi", {"beriberi", "beri"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Qaddafi", {"Muammar Qaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mo'ammar Gadhafi", {"Mo'ammar Gadhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Kaddafi", {"Muammar Kaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Qadhafi", {"Muammar Qadhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moammar El Kadhafi", {"Moammar El Kadhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Gadafi", {"Muammar Gadafi", NULL, "d"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'ammar al-Qadafi", {"Mu'ammar al-Qadafi", NULL, "d"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moamer El Kazzafi", {"Moamer El Kazzafi", NULL, "zz"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moamar al-Gaddafi", {"Moamar al-Gaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'ammar Al Qathafi", {"Mu'ammar Al Qathafi", NULL, "th"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Al Qathafi", {"Muammar Al Qathafi", NULL, "th"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mo'ammar el-Gadhafi", {"Mo'ammar el-Gadhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moamar El Kadhafi", {"Moamar El Kadhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar al-Qadhafi", {"Muammar al-Qadhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'ammar al-Qadhdhafi", {"Mu'ammar al-Qadhdhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'ammar Qadafi", {"Mu'ammar Qadafi", NULL, "d"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moamar Gaddafi", {"Moamar Gaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'ammar Qadhdhafi", {"Mu'ammar Qadhdhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Khaddafi", {"Muammar Khaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar al-Khaddafi", {"Muammar al-Khaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'amar al-Kadafi", {"Mu'amar al-Kadafi", NULL, "d"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Ghaddafy", {"Muammar Ghaddafy", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Ghadafi", {"Muammar Ghadafi", NULL, "d"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Ghaddafi", {"Muammar Ghaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muamar Kaddafi", {"Muamar Kaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Quathafi", {"Muammar Quathafi", NULL, "th"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muammar Gheddafi", {"Muammar Gheddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Muamar Al-Kaddafi", {"Muamar Al-Kaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moammar Khadafy", {"Moammar Khadafy", NULL, "d"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Moammar Qudhafi", {"Moammar Qudhafi", NULL, "dh"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mu'ammar al-Qaddafi", {"Mu'ammar al-Qaddafi", NULL, "dd"}},
  {0, "M[ou]'?am+[ae]r .*([AEae]l[- ])?[GKQ]h?[aeu]+([dtz][dhz]?)+af[iy]", "Mulazim Awwal Mu'ammar Muhammad Abu Minyar al-Qadhafi", {"Mu'ammar Muhammad Abu Minyar al-Qadhafi", NULL, "dh"}},
  {0, "[[:digit:]]+", "01234", {"01234"}},
  {1, "[[:alpha:]]+", "01234"},
  {0, "^[[:digit:]]*$", "01234", {"01234"}},
  {1, "^[[:digit:]]*$", "01234a"},
  {0, "^[[:alnum:]]*$", "01234a", {"01234a"}},
  {0, "^[[:xdigit:]]*$", "01234a", {"01234a"}},
  {1, "^[[:xdigit:]]*$", "01234g"},
  {0, "^[[:alnum:][:space:]]*$", "Hello world", {"Hello world"}},
